# Generated by Django 3.1.5 on 2021-01-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('startingBid', models.IntegerField()),
                ('imageURL', models.URLField()),
                ('category', models.CharField(max_length=25)),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True)),
                ('dateTimeEndListing', models.DateTimeField()),
            ],
        ),
    ]
