# Generated by Django 3.1.5 on 2021-01-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='follower',
        ),
        migrations.AddField(
            model_name='user',
            name='watchList',
            field=models.ManyToManyField(to='auctions.Listing'),
        ),
    ]
