# Generated by Django 3.1.5 on 2021-01-29 04:41

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210127_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidAmount', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biddingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_by_user', to='auctions.listing')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_on_listing', to='auctions.listing')),
            ],
        ),
    ]
